# ========== STARSHIP CUSTOM CONFIG ==========
add_newline = false

format = """
[>](bold blue)$time$battery$username[>](bold blue)$directory[>](blue)$git_branch$git_status[>](green)$python$nodejs$cmd_duration
$character
"""

[character]
success_symbol = "[>](bold green)"
error_symbol = "[x](bold red)"
vicmd_symbol = "[V](bold yellow)"

[time]
disabled = false
time_format = "%H:%M"
format = "[ $time ](dimmed white)"
style = "bold dimmed white"

[battery]
disabled = false
format = " [$percentage ]($style)"
full_symbol = "Full"
charging_symbol = "+"
discharging_symbol = "-"
[[battery.display]]
threshold = 30
style = "bold red"
[[battery.display]]
threshold = 60
style = "bold yellow"
[[battery.display]]
threshold = 100
style = "bold green"

[username]
style_user = "blue bold"
style_root = "red bold"
show_always = true

[directory]
style = "cyan bold"
truncation_length = 3
truncate_to_repo = false
format = "[ $path ]($style)"

[git_branch]
format = " [$branch]($style)"
style = "bold purple"

[git_status]
format = " [$all_status$ahead_behind]($style)"
style = "yellow"

[python]
format = " [py $version]($style)"
style = "bold green"

[nodejs]
format = " [node $version]($style)"
style = "bold yellow"

[cmd_duration]
min_time = 100
format = " [took $duration]($style)"
style = "bold italic yellow"

[jobs]
style = "bold red"
symbol = "+"

[memory_usage]
disabled = false
threshold = 75
symbol = "RAM:"
style = "bold dimmed blue"
